name: Deploy to Github Pages Branch
on: 
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node JS LTS
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install npm dependencies
      run: npm install

    - name: Run build steps
      run: ./deploy.sh
